global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

rule_files: ["rules/*.yml"]

alerting:
  alertmanagers:
    - timeout: "10s"
      scheme: http
      static_configs:
        - targets: ["alertmanager:9093"]

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "kafka"
    scrape_interval: 10s
    scrape_timeout: 10s
    scheme: http
    static_configs:
      - targets:
        - jmx-exporter-broker:5556
        - jmx-exporter-controller:5556
        - kafka-exporter:9308
        - kafka-minion:8080
        - broker-1:9200
        - broker-2:9200
        - broker-3:9200
        - broker-4:9200
        - broker-5:9200
